apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-27T18:34:58Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "890"
  uid: 92184aef-5328-410a-aa5c-f3cb075169dc
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.182.90
  clusterIPs:
  - 10.111.182.90
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30114
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
